-- display all tables
SELECT table_name FROM USER_TABLES;

SELECT COUNT(*) FROM T_LOG;

SELECT COUNT(MYID) FROM T_EMPLOYEE_BASE;

-- select
SELECT MYID, SEX, MARRIED, E_NAME, E_CODE FROM T_EMPLOYEE_BASE;

-- output to like csv format
SELECT MYID ||','|| SEX ||','|| MARRIED ||','|| E_NAME ||','|| E_CODE FROM T_EMPLOYEE_BASE;
