-- display all tables
SELECT table_name FROM USER_TABLES;

SELECT COUNT(MYID) FROM T_LOG;

SELECT COUNT(MYID)
  FROM T_EMPLOYEE_BASE;

-- select
SELECT MYID ID,
       E_NAME NAME
  FROM T_EMPLOYEE_BASE
 WHERE rownum <= 10;

SELECT rownum, MYID ID, E_NAME name
  FROM T_EMPLOYEE_BASE
 WHERE rownum <= 10;
